### ISSUE TITLE
MISP An Internal Error Has Occurred

### ISSUE THREAD

**Issue by IrArTr** [MISP/x_old_misp_docker#105]
I have a problem, when I want to see an event created and the same when I create a tag and want to see the list of tags gives me the following error:

An Internal Error Has Occurred.
Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.

Please can you help me I don't understand what is the problem

**Comment by CloudArtAdmins** [comment]
I was getting that error when trying to delegate events.
Happen to know if this issue has affected you since an update?

**Comment by IrArTr** [comment]
> I was getting that error when trying to delegate events.
> Happen to know if this issue has affected you since an update?

no, it's the first time I install it

**Comment by Stefan249** [comment]
Some here.
It's related to https://github.com/MISP/MISP/issues/6824

**Comment by blabut** [comment]
Hi all, did anyone find any fix on this issue ? I am getting the same error after a fresh install when trying to access a specific event record from the DB.

**Comment by Stefan249** [comment]
Replace the following line with (..Misp/app/Model/Sighting.php):
 334             'group' => ['date_sighting', 'org_id', 'attribute_id', 'type', 'date'],
 371             'group' => ['date_sighting', ucfirst($context) . 'Tag.id', 'date'],

**Comment by d4vydm** [comment]
@Stefan249 Confirmed, fixes issue.

**Comment by mainakdey36** [comment]
Facing a similar issue. The error log is given below. Please help.

2021-12-19 07:46:31 Warning: SplFileInfo::openFile(/var/www/MISP/app/tmp/cache/persistent/myapp_cake_core_cake_console_eng): failed to open stream: No space left on device in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Cache/Engine/FileEngine.php, line 364]
2021-12-19 07:46:31 Warning: _cake_core_ cache was unable to write 'cake_console_eng' to File cache in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Cache/Cache.php, line 327]
2021-12-19 07:46:31 Warning: SplFileInfo::openFile(/var/www/MISP/app/tmp/cache/persistent/myapp_cake_core_cake_console_eng): failed to open stream: No space left on device in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Cache/Engine/FileEngine.php, line 364]
2021-12-19 07:46:31 Warning: _cake_core_ cache was unable to write 'cake_console_eng' to File cache in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Cache/Cache.php, line 327]
2021-12-20 13:18:59 Error: [RedisException] MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
Request URL: /users/routeafterlogin
Stack Trace:
#0 /var/www/MISP/app/Controller/AppController.php(663): Redis->exec()
#1 /var/www/MISP/app/Controller/AppController.php(251): AppController->__logAccess()
#2 /var/www/MISP/app/Controller/UsersController.php(33): AppController->beforeFilter()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): UsersController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#7 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#8 {main}
2021-12-20 13:19:12 Error: [RedisException] MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
Request URL: /users/routeafterlogin
Stack Trace:
#0 /var/www/MISP/app/Controller/AppController.php(663): Redis->exec()
#1 /var/www/MISP/app/Controller/AppController.php(251): AppController->__logAccess()
#2 /var/www/MISP/app/Controller/UsersController.php(33): AppController->beforeFilter()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): UsersController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#7 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#8 {main}
2021-12-20 13:19:16 Error: [RedisException] MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
Request URL: /users/login
Stack Trace:
#0 /var/www/MISP/app/Controller/AppController.php(663): Redis->exec()
#1 /var/www/MISP/app/Controller/AppController.php(251): AppController->__logAccess()
#2 /var/www/MISP/app/Controller/UsersController.php(33): AppController->beforeFilter()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): UsersController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#7 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#8 {main}
2021-12-20 13:19:23 Error: [RedisException] MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Controller/AppController.php(663): Redis->exec()
#1 /var/www/MISP/app/Controller/AppController.php(251): AppController->__logAccess()
#2 /var/www/MISP/app/Controller/EventsController.php(63): AppController->beforeFilter()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): EventsController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#7 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#8 {main}
2021-12-20 13:19:30 Error: [RedisException] MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Controller/AppController.php(663): Redis->exec()
#1 /var/www/MISP/app/Controller/AppController.php(251): AppController->__logAccess()
#2 /var/www/MISP/app/Controller/EventsController.php(63): AppController->beforeFilter()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): EventsController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#7 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#8 {main}
2021-12-20 13:19:38 Error: [RedisException] MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
Request URL: /users/login
Stack Trace:
#0 /var/www/MISP/app/Controller/AppController.php(663): Redis->exec()
#1 /var/www/MISP/app/Controller/AppController.php(251): AppController->__logAccess()
#2 /var/www/MISP/app/Controller/UsersController.php(33): AppController->beforeFilter()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): UsersController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#7 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#8 {main}
2021-12-20 13:20:12 Error: [RedisException] MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
Request URL: /users/login
Stack Trace:
#0 /var/www/MISP/app/Controller/AppController.php(663): Redis->exec()
#1 /var/www/MISP/app/Controller/AppController.php(251): AppController->__logAccess()
#2 /var/www/MISP/app/Controller/UsersController.php(33): AppController->beforeFilter()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): UsersController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#7 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#8 {main}
2021-12-20 13:20:24 Error: [RedisException] MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
Request URL: /users/login?_=1639742189377
Stack Trace:
#0 /var/www/MISP/app/Controller/AppController.php(663): Redis->exec()
#1 /var/www/MISP/app/Controller/AppController.php(251): AppController->__logAccess()
#2 /var/www/MISP/app/Controller/UsersController.php(33): AppController->beforeFilter()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): UsersController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#7 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#8 {main}
2021-12-20 13:21:27 Error: [RedisException] MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Controller/AppController.php(663): Redis->exec()
#1 /var/www/MISP/app/Controller/AppController.php(251): AppController->__logAccess()
#2 /var/www/MISP/app/Controller/EventsController.php(63): AppController->beforeFilter()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): EventsController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#7 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#8 {main}
2021-12-20 13:24:15 Error: [RedisException] MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Controller/AppController.php(663): Redis->exec()
#1 /var/www/MISP/app/Controller/AppController.php(251): AppController->__logAccess()
#2 /var/www/MISP/app/Controller/EventsController.php(63): AppController->beforeFilter()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): EventsController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#7 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#8 {main}
2021-12-20 13:24:20 Error: [RedisException] MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Controller/AppController.php(663): Redis->exec()
#1 /var/www/MISP/app/Controller/AppController.php(251): AppController->__logAccess()
#2 /var/www/MISP/app/Controller/EventsController.php(63): AppController->beforeFilter()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): EventsController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#7 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#8 {main}
2021-12-20 13:24:49 Error: [RedisException] MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Controller/AppController.php(663): Redis->exec()
#1 /var/www/MISP/app/Controller/AppController.php(251): AppController->__logAccess()
#2 /var/www/MISP/app/Controller/EventsController.php(63): AppController->beforeFilter()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): EventsController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#7 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#8 {main}
2021-12-20 13:28:01 Error: [RedisException] MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
Request URL: /users/routeafterlogin
Stack Trace:
#0 /var/www/MISP/app/Controller/AppController.php(663): Redis->exec()
#1 /var/www/MISP/app/Controller/AppController.php(251): AppController->__logAccess()
#2 /var/www/MISP/app/Controller/UsersController.php(33): AppController->beforeFilter()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): UsersController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#7 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#8 {main}
2021-12-20 13:30:53 Error: [RedisException] MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
Request URL: /users/routeafterlogin
Stack Trace:
#0 /var/www/MISP/app/Controller/AppController.php(663): Redis->exec()
#1 /var/www/MISP/app/Controller/AppController.php(251): AppController->__logAccess()
#2 /var/www/MISP/app/Controller/UsersController.php(33): AppController->beforeFilter()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): UsersController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#7 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#8 {main}
2021-12-20 13:47:13 Error: [RedisException] MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
Request URL: /users/login
Stack Trace:
#0 /var/www/MISP/app/Controller/AppController.php(663): Redis->exec()
#1 /var/www/MISP/app/Controller/AppController.php(251): AppController->__logAccess()
#2 /var/www/MISP/app/Controller/UsersController.php(33): AppController->beforeFilter()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): UsersController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#7 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#8 {main}
2021-12-20 13:48:43 Error: [RedisException] MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
Request URL: /users/routeafterlogin
Stack Trace:
#0 /var/www/MISP/app/Controller/AppController.php(663): Redis->exec()
#1 /var/www/MISP/app/Controller/AppController.php(251): AppController->__logAccess()
#2 /var/www/MISP/app/Controller/UsersController.php(33): AppController->beforeFilter()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): UsersController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#7 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#8 {main}
2021-12-20 13:49:57 Error: [RedisException] MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
Request URL: /users/
Stack Trace:
#0 /var/www/MISP/app/Controller/AppController.php(663): Redis->exec()
#1 /var/www/MISP/app/Controller/AppController.php(251): AppController->__logAccess()
#2 /var/www/MISP/app/Controller/UsersController.php(33): AppController->beforeFilter()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): UsersController->beforeFilter()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#7 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#8 {main}
