### ISSUE TITLE
An Internal Error Has Occurred. on initial install

### ISSUE THREAD

**Issue by DigiAngel** [MISP/x_old_misp_docker#171]
Seeing:
~~~
2023-06-30 19:37:30 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User.totp' in 'field list'
Request URL: /users/login
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource()
#6 /var/www/MISP/app/Controller/UsersController.php(1186): Model->find()
#7 [internal function]: UsersController->login()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#11 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#12 {main}
~~~

in the /var/www/MISP/app/tmp/log/error.log

**Comment by DigiAngel** [comment]
Closed to do lack of developer interest.

**Comment by righel** [comment]
Hello, please refer to: https://github.com/MISP/MISP/issues/9149#issuecomment-1598146386
The error is not Docker related.
