### ISSUE TITLE
Unable to import exported MISP events as XML

### ISSUE THREAD

**Issue by notmonalisa** [MISP/x_old_misp_docker#80]
I recently updated the MISP project from 2.4.105 to 2.4.120 and I am unable to import the exported events as it is showing the following error:
2020-02-18 06:00:26 Error: [XmlException] Xml cannot be read.
Request URL: /events/add_misp_export
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/Xml.php(107): Xml::_loadXml('<?xml version="...', Array)
#1 /var/www/MISP/app/Controller/EventsController.php(3194): Xml::build('<?xml version="...')
#2 /var/www/MISP/app/Controller/EventsController.php(2135): EventsController->_addMISPExportFile('xml', false, '1')
#3 [internal function]: EventsController->add_misp_export()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#7 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}

I have changed buffer memory and max upload to 5G for now in the php.ini file.
Can anyone help me?
Thank you in advance.

**Comment by notmonalisa** [comment]
Never mind. It worked for me in 2.4.124
