### ISSUE TITLE
OpenCV Python Lib - Dependency Missing

### ISSUE THREAD

**Issue by itzdan** [MISP/x_old_misp_docker#94]
Following was experienced during building of docker MISP inside ubuntu/bionic. 

```
Collecting opencv-python==4.4.0.44 (from -r REQUIREMENTS (line 56))
  Downloading https://files.pythonhosted.org/packages/38/a9/cd39fd25df434b5d9451dc266c12b72f68282a2b9bd5d7b4aa2d57d6c20e/opencv-python-4.4.0.44.tar.gz (88.9MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-fcrux1i_/opencv-python/setup.py", line 9, in <module>
        import skbuild
    ModuleNotFoundError: No module named 'skbuild'
```

After some troubleshooting, adding the following resolves this missing dependency;

    pip3 install --upgrade pip setuptools wheel && \
    pip3 install scikit-build && \    
    pip3 install opencv-python && \

**Comment by itzdan** [comment]
@stevengoossensB  ping

**Comment by stevengoossensB** [comment]
You can add a pull request to fix this

**Comment by itzdan** [comment]
PR 97 requested

https://github.com/MISP/misp-docker/pull/97

**Comment by narly-david** [comment]
Can this be closed?
